# From https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs#using-the-nodejs-starter-workflow
name: Node.js and Solana CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [favorites, escrow]

    steps:
      - uses: actions/checkout@v4
      # See https://github.com/metaDAOproject/setup-anchor for docs
      # TODO: change to metadaoproject/setup-anchor when https://github.com/metaDAOproject/setup-anchor/issues/9 is resolved
      - uses: mikemaccana/setup-anchor@v3
        with:
          anchor-version: "latest"
          solana-cli-version: "2.0.17"
          node-version: "22.11.0"

      # git will keep outputting:
      #   hint: Using 'master' as the name for the initial branch. This default branch name
      #   hint: is subject to change.
      # Unless we set this.
      - name: Set a default branch name for git
        run: |
          git config --global init.defaultBranch main

      - name: Print versions and debugging info
        run: |
          echo Linux version:
          lsb_release -a
          echo Solana version:
          solana -V
          echo Anchor version:
          anchor -V
          echo build-sbf version:
          cargo build-sbf --version
          echo Path:
          echo $PATH | tr ':' '\n' | sort

      # Fixes:
      #   Error: Unable to read keypair file
      # during 'anchor test'
      - name: Make a default keypair
        run: |
          solana-keygen new --no-bip39-passphrase

      # TODO: remove RUSTUP_TOOLCHAIN fix once issue below is resolved
      # https://stackoverflow.com/questions/79225593/unexpected-cfg-condition-value-solana
      - name: Test the ${{ matrix.project }} project builds and tests pass
        run: |
          cd labs/${{ matrix.project }}
          echo "----------------------------------------"
          echo "Creating a keypair..."
          solana-keygen new --no-bip39-passphrase -s -o deleteme.json
          echo SECRET_KEY="$(cat deleteme.json)"> .env
          cat .env
          echo "----------------------------------------"
          echo "Installing packages..."
          npm i
          echo "----------------------------------------"
          echo "Running 'anchor test'..."
          RUSTUP_TOOLCHAIN="nightly-2024-11-19" anchor test 2>&1 | tee -a build.log
          echo "----------------------------------------"
          echo "build.log..."
          cat build.log
          echo "----------------------------------------"
          echo "Checking for errors or warnings in build.log..."
          grep -qiEvz 'error:|warning:|failed' build.log
          echo $?
